# Setup

In [32]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [33]:
from contextlib import redirect_stdout
import numpy as np
import os
import pandas as pd
import plotly.express as px

from cost import *
from plotting import *
from prices import *
from inflation import *
from regression import *
from utils import *

In [34]:
estimation_method = 'hardware-acquisition'  # hardware-capex-energy, hardware-acquisition, cloud
compute_threshold_method = 'top_n'  # top_n, window_percentile
compute_threshold = 5  # e.g. 10 to select top 10; 75 to select top 25%
variant = '2025-11-28_lms_since_2020'  # whatever else distinguishes this run, e.g. 'excluding-AlphaGo'
exclude_models_containing = []  # ['GNMT', 'AlphaZero', 'AlphaGo Master', 'AlphaGo Zero']

estimation_method_lookup = {
    'hardware-capex-energy': estimate_hardware_capex_energy,
    'hardware-acquisition': estimate_hardware_acquisition_cost,
    'cloud': estimate_cloud_costs,
}
cost_estimation_function = estimation_method_lookup[estimation_method]

results_dir = f'results/{estimation_method}-{compute_threshold_method}={compute_threshold}-{variant}/'
os.makedirs(results_dir, exist_ok=True)

# Load data

In [35]:
frontier_pcd_df, hardware_df, price_df = load_data_for_cost_estimation(
    compute_threshold_method=compute_threshold_method, compute_threshold=compute_threshold,
)

In [36]:
# Filter to post 2020
frontier_pcd_df = frontier_pcd_df[frontier_pcd_df['Publication date'] >= '2020-01-01']

In [37]:
len(frontier_pcd_df), len(hardware_df), len(price_df)

(41, 5786, 595)

# Cost estimation

In [38]:
with open(f'{results_dir}/cost_estimation.out', 'w') as f:
    with redirect_stdout(f):
        cost_df = cost_estimation_function(frontier_pcd_df, hardware_df, price_df)

In [39]:
if estimation_method == 'hardware-capex-energy':
    frontier_pcd_df_copy = frontier_pcd_df.copy()
    with open(f'{results_dir}/component_cost_estimation.out', 'w') as f:
        with redirect_stdout(f):
            component_cost_df = cost_estimation_function(frontier_pcd_df_copy, hardware_df, price_df, separate_components=True)

In [40]:
cost_df

,Model,Domain,Task,Organization,Organization categorization,Authors,Publication date,Reference,Link,Citations,...,Training dataset size notes,Training dataset size (text tokens),Training dataset size (words),From field: Model versions,Reasoning/thinking settings,Input cost (per MTok),Cached input cost (per MTok),Output cost (per MTok),Model versions,Cost
3,Grok 4,"Language,Multimodal,Vision","Language modeling/generation,Question answerin...",xAI,Industry,NaN,2025-07-09,Grok 4,https://x.ai/news/grok-4,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
135,Llama 4 Behemoth (preview),"Multimodal,Language,Vision","Chat,Code generation,Visual question answering...",Meta AI,Industry,NaN,2025-04-05,The Llama 4 herd: The beginning of a new era o...,https://ai.meta.com/blog/llama-4-multimodal-in...,NaN,...,"""The overall data mixture for training consist...",NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.757625e+09
196,GPT-4.5,"Language,Vision,Multimodal","Language modeling/generation,Question answerin...",OpenAI,Industry,"Foundational contributors\nAlex Paino, Ali Kam...",2025-02-27,Introducing GPT-4.5,https://openai.com/index/introducing-gpt-4-5/,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
208,Claude 3.7 Sonnet,"Language,Vision,Multimodal","Language modeling/generation,Question answerin...",Anthropic,Industry,NaN,2025-02-24,Claude 3.7 Sonnet,https://www.anthropic.com/news/claude-3-7-sonnet,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
226,Grok 3,"Language,Vision,Multimodal","Chat,Language modeling/generation,Question ans...",xAI,Industry,NaN,2025-02-17,Grok 3 Beta — The Age of Reasoning Agents,https://x.ai/blog/grok-3,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,4.394062e+09
424,Doubao-pro,Language,"Language modeling/generation,Question answerin...",ByteDance,Industry,NaN,2024-10-28,Doubao General Model Pro (Doubao-pro),https://www.volcengine.com/docs/6360/1264663,NaN,...,[Speculative] Doubao's pre-training data volum...,8350000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
688,Grok-2,"Language,Vision,Multimodal","Chat,Language modeling/generation,Question ans...",xAI,Industry,NaN,2024-08-13,Grok-2 Beta Release,https://x.ai/blog/grok-2,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
735,Mistral Large 2,Language,"Language modeling/generation,Translation,Code ...",Mistral AI,Industry,"Albert Jiang, Alexandre Sablayrolles, Alexis T...",2024-07-24,"Top-tier reasoning for high-complexity tasks, ...",https://mistral.ai/news/mistral-large-2407/,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
740,Llama 3.1-405B,Language,"Language modeling/generation,Question answerin...",Meta AI,Industry,"Abhimanyu Dubey, Abhinav Jauhri, Abhinav Pande...",2024-07-23,The Llama 3 Herd of Models,https://ai.meta.com/research/publications/the-...,NaN,...,15.6T tokens,15600000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,8.999039e+08
804,Claude 3.5 Sonnet,"Multimodal,Language,Vision","Chat,Image captioning,Code generation,Language...",Anthropic,Industry,NaN,2024-06-20,Claude 3.5 Sonnet,https://www-cdn.anthropic.com/fed9cc193a14b841...,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
815,Nemotron-4 340B,Language,"Language modeling/generation,Chat,Question ans...",NVIDIA,Industry,"Bo Adler, Niket Agarwal, Ashwath Aithal, Dong ...",2024-06-14,NVIDIA Releases Open Synthetic Data Generation...,https://blogs.nvidia.com/blog/nemotron-4-synth...,NaN,...,9T training tokens.\n\nThey first train on an ...,9000000000000,6750000000000,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,3.374640e+08
1056,Aramco Metabrain AI,Language,Language modeling/generation,Saudi Aramco,"Industry,Government",Saudi Aramco,2024-03-04,Saudi Aramco unveils industry’s first generati...,https://www.offshore-technology.com/news/saudi...,NaN,...,"""The AI was trained using seven trillion data ...",7000000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1078,Mistral Large,Language,Chat,Mistral AI,Industry,NaN,2024-02-26,"Mistral Large, our new flagship model",https://mistral.ai/news/mistral-large/,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1216,Gemini 1.0 Ultra,"Multimodal,Language,Vision","Language modeling,Visual question answering,Ch...",Google DeepMind,Industry,Gemini Team,2023-12-06,Gemini: A Family of Highly Capable Multimodal ...,https://storage.googleapis.com/deepmind-media/...,633.0,...,Gemini models are trained with a sequence leng...,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,5.963101e+08
1246,Inflection-2,Language,"Language modeling,Language modeling/generation...",Inflection AI,Industry,NaN,2023-11-22,Inflection-2: The Next Step Up,https://inflection.ai/inflection-2,NaN,...,I didn't find any information about the dataset,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,2.746289e+08
1347,Amazon Titan,"Language,Image generation","Semantic search,Image generation,Language mode...",Amazon,Industry,NaN,2023-09-28,NaN,https://aws.amazon.com/bedrock/titan/,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,4.225679e+08
1374,Falcon-180B,Language,"Language modeling,Language modeling/generation...",Technology Innovation Institute,Government,"Ebtesam Almazrouei, Hamza Alobeidli, Abdulaziz...",2023-09-06,The Falcon Series of Open Language Models,https://falconllm.tii.ae/falcon-180b.html; htt...,535.0,...,3.5 trillion tokens * (~3 words per 4 tokens) ...,3500000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.257877e+08
1456,Claude 2,Language,"Language modeling,Chat,Language modeling/gener...",Anthropic,Industry,NaN,2023-07-11,NaN,"https://www.anthropic.com/index/claude-2, http...",NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1532,PaLM 2,Language,"Language modeling,Language modeling/generation",Google,Industry,"Andrew M. Dai, David R. So, Dmitry Lepikhin, J...",2023-05-10,PaLM 2 Technical Report,https://arxiv.org/abs/2305.10403,1734.0,...,"""The pre-training corpus is significantly larg...",3600000000000,2700000000000,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1565,SenseChat,Language,"Chat,Language modeling/generation",SenseTime,Industry,NaN,2023-04-10,SenseTime Launches “SenseNova” Foundation Mode...,https://www.sensetime.com/en/news-detail/51166...,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1603,GPT-4,"Multimodal,Language,Vision","Language modeling,Language modeling/generation...",OpenAI,Industry,"OpenAI, Josh Achiam, Steven Adler, Sandhini Ag...",2023-03-15,GPT-4 Technical Report,https://arxiv.org/abs/2303.08774,18329.0,...,"Semianalysis reports 13T tokens, which represe...",5416666666667,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,7.677469e+08
1691,GPT-3.5,Language,Language modeling,OpenAI,Industry,NaN,2022-11-28,NaN,https://platform.openai.com/docs/models/gpt-3-5,NaN,...,I didn't find any information about the dataset,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1847,PaLM (540B),Language,"Language modeling,Code generation,Translation",Google Research,Industry,"Aakanksha Chowdhery, Sharan Narang, Jacob Devl...",2022-04-04,PaLM: Scaling Language Modeling with Pathways,https://arxiv.org/abs/2204.02311,6954.0,...,"""The PaLM pretraining dataset consists of a hi...",780000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,6.427595e+07
1851,Chinchilla,Language,Language modeling,DeepMind,Industry,"Jordan Hoffmann, Sebastian Borgeaud, Arthur Me...",2022-03-29,Training Compute-Optimal Large Language Models,https://arxiv.org/abs/2203.15556,2378.0,...,"""Table 1 shows Chinchilla was training on 1.4 ...",1400000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1893,ERNIE 3.0 Titan,Language,"Language modeling,Language modeling/generation...","Baidu,Peng Cheng Laboratory","Industry,Academia","Shuohuan Wang, Yu Sun, Yang Xiang, Zhihua Wu, ...",2021-12-23,ERNIE 3.0 Titan: Exploring Larger-scale Knowle...,https://arxiv.org/abs/2112.12731,80.0,...,"""To ensure the success of the pre-training of ...",668000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1902,EXAONE 1.0,"Multimodal,Language,Vision","Translation,Language modeling/generation,Visua...",LG,Industry,NaN,2021-12-14,NaN,https://www.lgcorp.com/media/release/27387#:~:...,NaN,...,I am not finding the source of the quote about...,NaN,600000000000,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1903,GLaM,Language,"Language modeling/generation,Question answering",Google,Industry,"Nan Du, Yanping Huang, Andrew M. Dai, Simon To...",2021-12-13,GLaM: Efficient Scaling of Language Models wit...,https://arxiv.org/abs/2112.06905,955.0,...,"The dataset is made of 1.6 trillion tokens, bu...",600000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.071266e+07
1907,Gopher (280B),Language,"Language modeling,Question answering",DeepMind,Industry,"Jack W. Rae, Sebastian Borgeaud, Trevor Cai, K...",2021-12-08,"""Scaling Language Models: Methods, Analysis & ...",https://arxiv.org/abs/2112.11446,1430.0,...,"""We train all models for 300 billion tokens wi...",300000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,4.375458e+07
1949,Yuan 1.0,Language,Language modeling,Inspur,Industry,"Shaohua Wu, Xudong Zhao, Tong Yu, Rongguo Zhan...",2021-10-12,Yuan 1.0: Large-Scale Pre-trained Language Mod...,https://arxiv.org/abs/2110.04725,61.0,...,Table 2: 180B training tokens (though the avai...,180000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1951,Megatron-Turing NLG 530B,Language,"Language modeling,Language modeling/generation...","Microsoft,NVIDIA","Industry,Industry","Shaden Smith, Mostofa Patwary, Brandon Norick,...",2021-10-11,Using DeepSpeed and Megatron to Train Megatron...,https://arxiv.org/abs/2201.11990,789.0,...,"""""""Our training dataset consists of 339 billio...",270000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.375802e+08
1959,HyperCLOVA 82B,Language,"Language modeling/generation,Chat,Translation,...","NAVER,Search Solutions","Industry,Industry","Boseop Kim, HyoungSeok Kim, Sang-Woo Lee, Gich...",2021-09-10,What Changes Can Large-scale Language Models B...,https://arxiv.org/abs/2109.04650,125.0,...,"""However, experiments in Section 5.2 use the m...",300000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,3.144691e+07
1960,HyperCLOVA 204B,Language,Language modeling/generation,NAVER,Industry,NaN,2021-09-10,South Korea's Naver unveils 'hyperscale AI' pl...,https://aibusiness.com/nlp/south-korea-s-naver...,92.0,...,https://twitter.com/arankomatsuzaki/status/139...,560000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
1975,Jurassic-1-Jumbo,Language,"Language modeling/generation,Chat",AI21 Labs,Industry,"Opher Lieber, Or Sharir, Barak Lenz, Yoav Shoham",2021-08-11,Jurassic-1: Technical Details and Evaluation,https://uploads-ssl.webflow.com/60fd4503684b46...,55.0,...,"""Our model was trained with the conventional s...",300000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
2007,ByT5-XXL,Language,Language modeling,"Google,Google Research","Industry,Industry","Linting Xue, Aditya Barua, Noah Constant, Rami...",2021-05-28,ByT5: Towards a token-free future with pre-tra...,https://arxiv.org/abs/2105.13626,575.0,...,"""Like mT5, we set our sequence length to 1024 ...",1048576000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
2078,Switch,Language,Text autocompletion,Google,Industry,"William Fedus, Barret Zoph, Noam Shazeer",2021-01-11,Switch Transformers: Scaling to Trillion Param...,https://arxiv.org/abs/2101.03961,2720.0,...,"""In our protocol we pre-train with 2^20 (1,048...",86400000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.093865e+07
2120,mT5-XXL,Language,"Language modeling,Translation,Language modelin...","Google,Google Research","Industry,Industry","Linting Xue, Noah Constant, Adam Roberts, Mihi...",2020-10-20,mT5: A Massively Multilingual Pre-trained Text...,https://aclanthology.org/2021.naacl-main.41/,2775.0,...,The model was trained on a subset of 1 trillio...,1000000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN
2147,GShard (dense),Language,Translation,Google,Industry,"Dmitry Lepikhin, HyoukJoong Lee, Yuanzhong Xu,...",2020-06-30,GShard: Scaling Giant Models with Conditional ...,https://arxiv.org/abs/2006.16668,1439.0,...,"""We focus on improving the translation quality...",346666666667,260000000000,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.093865e+07
2163,GPT-3 175B (davinci),Language,"Text autocompletion,Language modeling/generation",OpenAI,Industry,"Tom B. Brown, Benjamin Mann, Nick Ryder, Melan...",2020-05-28,Language Models are Few-Shot Learners,https://arxiv.org/abs/2005.14165,48031.0,...,All models were trained for a total of 300 bil...,238000000000,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,2.299383e+08
2200,Turing-NLG,Language,"Text autocompletion,Language generation,Text s...",Microsoft,Industry,Corby Rosset,2020-02-13,Turing-NLG: A 17-billion-parameter language mo...,https://www.microsoft.com/en-us/research/blog/...,114.0,...,Authors say they pretrain on the same data as ...,46400000000,34800000000,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,5.886420e+06
2205,Meena,Language,"Text autocompletion,Chat",Google Brain,Industry,"Dongling Xiao, Han Zhang, Yukun Li, Yu Sun, Ha...",2020-01-28,Towards a Human-like Open-Domain Chatbot,https://arxiv.org/abs/2001.09977,967.0,...,"""After these filtering steps, the number of (c...",53333333333,40000000000,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,1.093865e+07
3102,GPT-5,"Multimodal,Language,Vision",NaN,OpenAI,Industry,NaN,2025-08-07,GPT-5 System Card,https://cdn.openai.com/gpt-5-system-card.pdf\n...,NaN,...,NaN,NaN,NaN,NaN,Unknown (use Inspect default),NaN,NaN,NaN,NaN,NaN

In [41]:
cost_df['Cost'].notna().sum()

19

In [42]:
cost_df.dropna(subset=['Cost'])['Training time (hours)'].notna().sum()

16

In [43]:
cost_df.dropna(subset=['Cost'])['Hardware utilization (MFU)'].notna().sum()

10

Exclusion

In [44]:
cost_df[['Model', 'Publication date']].tail(15)

                         Model Publication date
1903                      GLaM       2021-12-13
1907             Gopher (280B)       2021-12-08
1949                  Yuan 1.0       2021-10-12
1951  Megatron-Turing NLG 530B       2021-10-11
1959            HyperCLOVA 82B       2021-09-10
1960           HyperCLOVA 204B       2021-09-10
1975          Jurassic-1-Jumbo       2021-08-11
2007                  ByT5-XXL       2021-05-28
2078                    Switch       2021-01-11
2120                   mT5-XXL       2020-10-20
2147            GShard (dense)       2020-06-30
2163      GPT-3 175B (davinci)       2020-05-28
2200                Turing-NLG       2020-02-13
2205                     Meena       2020-01-28
3102                     GPT-5       2025-08-07

In [45]:
for kw in exclude_models_containing:
    cost_df = cost_df[cost_df['Model'].str.contains(kw) == False]
cost_df[['Model', 'Publication date']].tail(15)

                         Model Publication date
1903                      GLaM       2021-12-13
1907             Gopher (280B)       2021-12-08
1949                  Yuan 1.0       2021-10-12
1951  Megatron-Turing NLG 530B       2021-10-11
1959            HyperCLOVA 82B       2021-09-10
1960           HyperCLOVA 204B       2021-09-10
1975          Jurassic-1-Jumbo       2021-08-11
2007                  ByT5-XXL       2021-05-28
2078                    Switch       2021-01-11
2120                   mT5-XXL       2020-10-20
2147            GShard (dense)       2020-06-30
2163      GPT-3 175B (davinci)       2020-05-28
2200                Turing-NLG       2020-02-13
2205                     Meena       2020-01-28
3102                     GPT-5       2025-08-07

Use the below to check data availability for specific systems

In [46]:
# system = 'WizardLM-7B'
# row = cost_df.loc[cost_df['Model'] == system]
# print('Cost:', row['Cost'].values[0])
# print('Training hardware:', row['Training hardware'].values[0])
# print('Training time (hours):', row['Training time (hours)'].values[0])
# print('Hardware quantity:', row['Hardware quantity'].values[0])
# print('Hardware utilization:', row['Hardware utilization'].values[0])

# Apply inflation adjustment

In [47]:
cost_df['Cost'].dropna()

135     1.757625e+09
226     4.394062e+09
740     8.999039e+08
815     3.374640e+08
1216    5.963101e+08
1246    2.746289e+08
1347    4.225679e+08
1374    1.257877e+08
1603    7.677469e+08
1847    6.427595e+07
1903    1.071266e+07
1907    4.375458e+07
1951    1.375802e+08
1959    3.144691e+07
2078    1.093865e+07
2147    1.093865e+07
2163    2.299383e+08
2200    5.886420e+06
2205    1.093865e+07
Name: Cost, dtype: float64

In [48]:
cost_df = adjust_column_for_inflation(cost_df, 'Cost', 'data/PCU518210518210.csv', '2024-12-01')

In [49]:
cost_df['Cost (inflation-adjusted)'].dropna()

135     1.717996e+09
226     4.290914e+09
740     8.960449e+08
815     3.366319e+08
1216    5.979132e+08
1246    2.760095e+08
1347    4.263257e+08
1374    1.269063e+08
1603    7.780669e+08
1847    6.551546e+07
1903    1.108443e+07
1907    4.527306e+07
1951    1.423117e+08
1959    3.258600e+07
2078    1.138201e+07
2147    1.144186e+07
2163    2.420009e+08
2200    6.189765e+06
2205    1.152265e+07
Name: Cost (inflation-adjusted), dtype: float64

In [50]:
# Equal number of non-null values
assert cost_df['Cost (inflation-adjusted)'].notna().sum() == cost_df['Cost'].notna().sum()

# Regression

In [51]:
cost_df['Publication date (float)'] = datetime_to_float_year(pd.to_datetime(cost_df['Publication date']))

In [52]:
reg_results = fit_ols_regression(cost_df, ['Publication date (float)'], 'Cost (inflation-adjusted)', logy=True)
reg_results.summary()

/Users/bencottier/miniconda3/envs/epoch/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n>=20 ... continuing anyway, n=19

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.731
Model:                            OLS   Adj. R-squared:                  0.715
Method:                 Least Squares   F-statistic:                     46.22
Date:                Tue, 02 Dec 2025   Prob (F-statistic):           3.10e-06
Time:                        18:15:44   Log-Likelihood:                -10.736
No. Observations:                  19   AIC:                             25.47
Df Residuals:                      17   BIC:                             27.36
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -836.1239    124.178     -6.733      0.000   -1098.116    -574.132
x1             0.4174      0.061      6.798      0.000       0.288       0.547
==============================================================================
Omnibus:                        7.576   Durbin-Watson:                   2.403
Prob(Omnibus):                  0.023   Jarque-Bera (JB):                4.812
Skew:                           1.003   Prob(JB):                       0.0902
Kurtosis:                       4.432   Cond. No.                     2.43e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.43e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [53]:
with open(f'{results_dir}/regression_results.out', 'w') as f:
    with redirect_stdout(f):
        print_growth_rates(reg_results, round_digits=None)
print_growth_rates(reg_results, ci=90, round_digits=5)

N=19.0
R^2=0.73
0.41739 OOMs/year (90% CI: 0.31059, 0.52419)
2.6145x/year (90% CI: 2.0445x, 3.34342x)
doubling time of 8.65466 months (90% CI: 6.8913, 11.63078)

In [54]:
pred_start_year = 2020
pred_end_year = 2026
pred_start_date = f'{pred_start_year}-01-01'
pred_end_date = f'{pred_end_year}-01-01'

pred_years = pd.DataFrame({'Publication date (float)': np.linspace(pred_start_year, pred_end_year, 100)})
pred_years

    Publication date (float)
0                2020.000000
1                2020.060606
2                2020.121212
3                2020.181818
4                2020.242424
..                       ...
95               2025.757576
96               2025.818182
97               2025.878788
98               2025.939394
99               2026.000000

[100 rows x 1 columns]

In [55]:

predicted_cost_df = get_predictions(reg_results, pred_years, ['Publication date (float)'])
predicted_cost_df['Publication date'] = predicted_cost_df['Publication date (float)'].apply(float_year_to_datetime)
predicted_cost_df

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper,Publication date (float),Publication date
0,7.001533,0.190607,6.669951,7.333114,6.151199,7.851866,2020.000000,2020-01-01
1,7.026829,0.187491,6.700669,7.352989,6.178594,7.875063,2020.060606,2020-01-23
2,7.052125,0.184396,6.731348,7.372902,6.205946,7.898304,2020.121212,2020-02-14
3,7.077421,0.181326,6.761986,7.392857,6.233253,7.921590,2020.181818,2020-03-07
4,7.102718,0.178280,6.792581,7.412854,6.260515,7.944921,2020.242424,2020-03-29
...,...,...,...,...,...,...,...,...
95,9.404680,0.219129,9.023481,9.785879,8.533799,10.275561,2025.757576,2025-10-04
96,9.429977,0.222418,9.043057,9.816896,8.556576,10.303377,2025.818182,2025-10-26
97,9.455273,0.225720,9.062608,9.847937,8.579313,10.331233,2025.878788,2025-11-17
98,9.480569,0.229035,9.082138,9.879000,8.602009,10.359130,2025.939394,2025-12-09
99,9.505865,0.232363,9.101646,9.910085,8.624665,10.387066,2026.000000,2026-01-01

In [56]:
predicted_cost_df.to_csv(results_dir + 'predicted_cost_dataset.csv', index=False)

# Export data

In [57]:
keep_cols = [
    'Model',
    'Domain',
    'Task',
    'Model accessibility',
    'Reference',
    'Publication date',
    'Organization',
    'Parameters',
    'Training compute (FLOP)',
    'Training dataset size (gradients)',
    'Epochs',
    'Training time (hours)',
    'Training hardware',
    'Country (of organization)',
    'Base model',
    'Finetune compute (FLOP)',
    'Hardware quantity',
    'Hardware utilization (MFU)',
    'Training cloud compute vendor',
    'Training data center',
    # 'Training time (chip hours)',
    'Cost',
    'Cost (inflation-adjusted)',
]
cost_df[keep_cols]

,Model,Domain,Task,Model accessibility,Reference,Publication date,Organization,Parameters,Training compute (FLOP),Training dataset size (gradients),...,Training hardware,Country (of organization),Base model,Finetune compute (FLOP),Hardware quantity,Hardware utilization (MFU),Training cloud compute vendor,Training data center,Cost,Cost (inflation-adjusted)
3,Grok 4,"Language,Multimodal,Vision","Language modeling/generation,Question answerin...",API access,Grok 4,2025-07-09,xAI,NaN,5.000000e+26,NaN,...,NaN,United States of America,NaN,NaN,200000.0,NaN,NaN,"""we utilized Colossus, our 200,000 GPU cluster...",NaN,NaN
135,Llama 4 Behemoth (preview),"Multimodal,Language,Vision","Chat,Code generation,Visual question answering...",Unreleased,The Llama 4 herd: The beginning of a new era o...,2025-04-05,Meta AI,2.000000e+12,5.184000e+25,30000000000000,...,NVIDIA H100 SXM5 80GB,United States of America,NaN,NaN,32000.0,NaN,NaN,NaN,1.757625e+09,1.717996e+09
196,GPT-4.5,"Language,Vision,Multimodal","Language modeling/generation,Question answerin...",API access,Introducing GPT-4.5,2025-02-27,OpenAI,NaN,3.800000e+26,NaN,...,NaN,United States of America,NaN,NaN,NaN,NaN,Azure AI,NaN,NaN,NaN
208,Claude 3.7 Sonnet,"Language,Vision,Multimodal","Language modeling/generation,Question answerin...",API access,Claude 3.7 Sonnet,2025-02-24,Anthropic,NaN,3.350000e+25,NaN,...,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,Grok 3,"Language,Vision,Multimodal","Chat,Language modeling/generation,Question ans...",API access,Grok 3 Beta — The Age of Reasoning Agents,2025-02-17,xAI,NaN,3.500000e+26,NaN,...,NVIDIA H100 SXM5 80GB,United States of America,NaN,NaN,80000.0,NaN,NaN,xAI Memphis Colossus,4.394062e+09,4.290914e+09
424,Doubao-pro,Language,"Language modeling/generation,Question answerin...",API access,Doubao General Model Pro (Doubao-pro),2024-10-28,ByteDance,5.000000e+11,2.505000e+25,8350000000000,...,NaN,China,NaN,NaN,NaN,NaN,NaN,"There is no paper to reference, also no inform...",NaN,NaN
688,Grok-2,"Language,Vision,Multimodal","Chat,Language modeling/generation,Question ans...",API access,Grok-2 Beta Release,2024-08-13,xAI,NaN,2.960000e+25,NaN,...,NVIDIA H100 SXM5 80GB,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
735,Mistral Large 2,Language,"Language modeling/generation,Translation,Code ...",Open weights (non-commercial),"Top-tier reasoning for high-complexity tasks, ...",2024-07-24,Mistral AI,1.230000e+11,2.130000e+25,NaN,...,NaN,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
740,Llama 3.1-405B,Language,"Language modeling/generation,Question answerin...",Open weights (restricted use),The Llama 3 Herd of Models,2024-07-23,Meta AI,4.050000e+11,3.800000e+25,15600000000000,...,NVIDIA H100 SXM5 80GB,United States of America,NaN,NaN,16384.0,0.4042,NaN,NaN,8.999039e+08,8.960449e+08
804,Claude 3.5 Sonnet,"Multimodal,Language,Vision","Chat,Image captioning,Code generation,Language...",API access,Claude 3.5 Sonnet,2024-06-20,Anthropic,NaN,2.700000e+25,NaN,...,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,Nemotron-4 340B,Language,"Language modeling/generation,Chat,Question ans...",Open weights (unrestricted),NVIDIA Releases Open Synthetic Data Generation...,2024-06-14,NVIDIA,3.400000e+11,1.800000e+25,9000000000000,...,NVIDIA H100 SXM5 80GB,United States of America,NaN,NaN,6144.0,0.4107,NaN,NaN,3.374640e+08,3.366319e+08
1056,Aramco Metabrain AI,Language,Language modeling/generation,Unreleased,Saudi Aramco unveils industry’s first generati...,2024-03-04,Saudi Aramco,2.500000e+11,1.050000e+25,7000000000000,...,NaN,Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1078,Mistral Large,Language,Chat,API access,"Mistral Large, our new flagship model",2024-02-26,Mistral AI,NaN,1.120000e+25,NaN,...,NVIDIA H100 SXM5 80GB,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1216,Gemini 1.0 Ultra,"Multimodal,Language,Vision","Language modeling,Visual question answering,Ch...",API access,Gemini: A Family of Highly Capable Multimodal ...,2023-12-06,Google DeepMind,NaN,5.000000e+25,NaN,...,Google TPU v4,"United States of America,United Kingdom of Gre...",NaN,NaN,57000.0,NaN,NaN,NaN,5.963101e+08,5.979132e+08
1246,Inflection-2,Language,"Language modeling,Language modeling/generation...",Hosted access (no API),Inflection-2: The Next Step Up,2023-11-22,Inflection AI,NaN,1.001000e+25,NaN,...,NVIDIA H100 SXM5 80GB,United States of America,NaN,NaN,5000.0,NaN,NaN,NaN,2.746289e+08,2.760095e+08
1347,Amazon Titan,"Language,Image generation","Semantic search,Image generation,Language mode...",API access,NaN,2023-09-28,Amazon,2.000000e+11,4.800000e+24,4000000000000,...,NVIDIA A100,United States of America,NaN,NaN,13760.0,0.2696,NaN,NaN,4.225679e+08,4.263257e+08
1374,Falcon-180B,Language,"Language modeling,Language modeling/generation...",Open weights (restricted use),The Falcon Series of Open Language Models,2023-09-06,Technology Innovation Institute,1.800000e+11,3.760000e+24,3500000000000,...,NVIDIA A100 SXM4 40 GB,United Arab Emirates,NaN,NaN,4096.0,0.1892,Amazon Web Services,NaN,1.257877e+08,1.269063e+08
1456,Claude 2,Language,"Language modeling,Chat,Language modeling/gener...",API access,NaN,2023-07-11,Anthropic,NaN,3.866000e+24,NaN,...,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1532,PaLM 2,Language,"Language modeling,Language modeling/generation",API access,PaLM 2 Technical Report,2023-05-10,Google,3.400000e+11,7.340000e+24,3600000000000,...,Google TPU v4,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1565,SenseChat,Language,"Chat,Language modeling/generation",API access,SenseTime Launches “SenseNova” Foundation Mode...,2023-04-10,SenseTime,1.800000e+11,3.890000e+24,NaN,...,NaN,Hong Kong,NaN,NaN,NaN,NaN,NaN,SenseTime AI Computing Center,NaN,NaN
1603,GPT-4,"Multimodal,Language,Vision","Language modeling,Language modeling/generation...",API access,GPT-4 Technical Report,2023-03-15,OpenAI,1.800000e+12,2.100000e+25,5416666666667,...,NVIDIA A100 SXM4 40 GB,United States of America,NaN,NaN,25000.0,0.3400,NaN,NaN,7.677469e+08,7.780669e+08
1691,GPT-3.5,Language,Language modeling,API access,NaN,2022-11-28,OpenAI,NaN,2.578000e+24,NaN,...,NVIDIA A100 SXM4 40 GB,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1847,PaLM (540B),Language,"Language modeling,Code generation,Translation",Unreleased,PaLM: Scaling Language Modeling with Pathways,2022-04-04,Google Research,5.403500e+11,2.527200e+24,780000000000,...,Google TPU v4,United States of America,NaN,NaN,6144.0,0.4620,NaN,NaN,6.427595e+07,6.551546e+07
1851,Chinchilla,Language,Language modeling,Unreleased,Training Compute-Optimal Large Language Models,2022-03-29,DeepMind,7.000000e+10,5.760000e+23,1400000000000,...,"Google TPU v4,Google TPU v3",United Kingdom of Great Britain and Northern I...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1893,ERNIE 3.0 Titan,Language,"Language modeling,Language modeling/generation...",Hosted access (no API),ERNIE 3.0 Titan: Exploring Larger-scale Knowle...,2021-12-23,"Baidu,Peng Cheng Laboratory",2.600000e+11,1.042100e+24,668000000000,...,"NVIDIA Tesla V100 DGXS 32 GB,Huawei Ascend 910","China,China",NaN,NaN,1920.0,NaN,NaN,"Peng Cheng Cloud Brain II, Paper on Ernie 3.0",NaN,NaN
1902,EXAONE 1.0,"Multimodal,Language,Vision","Translation,Language modeling/generation,Visua...",Unreleased,NaN,2021-12-14,LG,3.000000e+11,1.695600e+24,NaN,...,NaN,Korea (Republic of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1903,GLaM,Language,"Language modeling/generation,Question answering",Unreleased,GLaM: Efficient Scaling of Language Models wit...,2021-12-13,Google,1.200000e+12,3.636311e+23,600000000000,...,Google TPU v4,United States of America,NaN,NaN,1024.0,0.2870,NaN,NaN,1.071266e+07,1.108443e+07
1907,Gopher (280B),Language,"Language modeling,Question answering",Unreleased,"""Scaling Language Models: Methods, Analysis & ...",2021-12-08,DeepMind,2.800000e+11,6.310000e+23,300000000000,...,Google TPU v3,United Kingdom of Great Britain and Northern I...,NaN,NaN,4096.0,0.3780,NaN,NaN,4.375458e+07,4.527306e+07
1949,Yuan 1.0,Language,Language modeling,API access,Yuan 1.0: Large-Scale Pre-trained Language Mod...,2021-10-12,Inspur,2.457300e+11,3.538000e+23,180000000000,...,NaN,China,NaN,NaN,2128.0,NaN,NaN,NaN,NaN,NaN
1951,Megatron-Turing NLG 530B,Language,"Language modeling,Language modeling/generation...",Unreleased,Using DeepSpeed and Megatron to Train Megatron...,2021-10-11,"Microsoft,NVIDIA",5.300000e+11,8.586000e+23,270000000000,...,NVIDIA A100 SXM4 80 GB,"United States of America,United States of America",NaN,NaN,4480.0,NaN,NaN,NaN,1.375802e+08,1.423117e+08
1959,HyperCLOVA 82B,Language,"Language modeling/generation,Chat,Translation,...",API access,What Changes Can Large-scale Language Models B...,2021-09-10,"NAVER,Search Solutions",8.200000e+10,1.476000e+23,300000000000,...,NVIDIA A100,"Korea (Republic of),Korea (Republic of)",NaN,NaN,1024.0,0.1995,NaN,NaN,3.144691e+07,3.258600e+07
1960,HyperCLOVA 204B,Language,Language modeling/generation,Hosted access (no API),South Korea's Naver unveils 'hyperscale AI' pl...,2021-09-10,NAVER,2.040000e+11,2.000000e+23,560000000000,...,NVIDIA A100,Korea (Republic of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975,Jurassic-1-Jumbo,Language,"Language modeling/generation,Chat",API access,Jurassic-1: Technical Details and Evaluation,2021-08-11,AI21 Labs,1.780000e+11,3.700000e+23,300000000000,...,NVIDIA A100,Israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,ByT5-XXL,Language,Language modeling,Open weights (unrestricted),ByT5: Towards a token-free future with pre-tra...,2021-05-28,"Google,Google Research",1.290000e+10,8.100000e+22,1048576000000,...,Google TPU v3,"United States of America,United States of America",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2078,Switch,Language,Text autocompletion,Open weights (unrestricted),Switch Transformers: Scaling to Trillion Param...,2021-01-11,Google,1.571000e+12,8.220000e+22,86400000000,...,Google TPU v3,United States of America,NaN,NaN,1024.0,NaN,NaN,NaN,1.093865e+07,1.138201e+07
2120,mT5-XXL,Language,"Language modeling,Translation,Language modelin...",Open weights (unrestricted),mT5: A Massively Multilingual Pre-trained Text...,2020-10-20,"Google,Google Research",1.300000e+10,8.200000e+22,1000000000000,...,NaN,"United States of America,United States of America",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2147,GShard (dense),Language,Translation,Unreleased,GShard: Scaling Giant Models with Conditional ...,2020-06-30,Google,2.300000e+09,4.765000e+22,346666666667,...,Google TPU v3,United States of America,NaN,NaN,1024.0,NaN,NaN,NaN,1.093865e+07,1.144186e+07
2163,GPT-3 175B (davinci),Language,"Text autocompletion,Language modeling/generation",API access,Language Models are Few-Shot Learners,2020-05-28,OpenAI,1.746000e+11,3.140000e+23,238000000000,...,NVIDIA Tesla V100 DGXS 32 GB,United States of America,NaN,NaN,10000.0,0.1966,Microsoft,NaN,2.299383e+08,2.420009e+08
2200,Turing-NLG,Language,"Text autocompletion,Language generation,Text s...",Unreleased,Turing-NLG: A 17-billion-parameter language mo...,2020-02-13,Microsoft,1.700000e+10,1.570000e+22,46400000000,...,NVIDIA Tesla V100 DGXS 32 GB,United States of America,NaN,NaN,256.0,NaN,NaN,NaN,5.886420e+06,6.189765e+06
2205,Meena,Language,"Text autocompletion,Chat",Unreleased,Towards a Human-like Open-Domain Chatbot,2020-01-28,Google Brain,2.600000e+09,1.120000e+23,53333333333,...,Google TPU v3,United States of America,NaN,NaN,1024.0,NaN,NaN,NaN,1.093865e+07,1.152265e+07
3102,GPT-5,"Multimodal,Language,Vision",NaN,API access,GPT-5 System Card,2025-08-07,OpenAI,NaN,6.600000e+25,NaN,...,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
cost_df[keep_cols].to_csv(results_dir + 'cost_dataset.csv', index=False)

# Plots

In [59]:
fig = px.scatter(
    cost_df,
    x='Publication date',
    y='Cost (inflation-adjusted)',
    text='Model',
    log_y=True,
)
fig.update_traces(textposition='top center')

# no legend
fig.update_layout(showlegend=False)

# axis labels
fig.update_xaxes(title_text='Publication date')
fig.update_yaxes(title_text='Cost (2025 USD, log scale)')

# title
fig.update_layout(title_text=get_cost_plot_title(estimation_method, compute_threshold_method, compute_threshold))

# update size
fig.update_layout(
    width=800,
    height=600,
    title_font=dict(
        size=16,
    )
)

# font size
fig.update_layout(
    font=dict(
        size=14,
    )
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=40, b=10))

save_plot(fig, results_dir, 'cost_scatter')

fig.show()

In [64]:
label_systems = ['VGG16', 'Xception', 'GPT-3 175B (davinci)', 'GPT-4', 'Grok 3']

tpu_mask = cost_df['Training hardware'].str.contains('TPU', na=False)
tpu_cost_df = cost_df.loc[tpu_mask]
gpu_cost_df = cost_df.loc[~tpu_mask]

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=gpu_cost_df['Publication date'],
    y=gpu_cost_df['Cost (inflation-adjusted)'],
    text=gpu_cost_df['Model'],
    mode='markers',
    showlegend=False,
))
fig.update_yaxes(type='log')
fig.add_trace(go.Scatter(
    x=tpu_cost_df['Publication date'],
    y=tpu_cost_df['Cost (inflation-adjusted)'],
    text=tpu_cost_df['Model'],
    mode='markers',
    marker_symbol='circle-open' if estimation_method != 'cloud' else 'circle',
    name='Using estimated cost of TPU' if estimation_method != 'cloud' else '',
    showlegend=estimation_method != 'cloud',
))
fig.add_trace(go.Scatter(
    x=gpu_cost_df.loc[gpu_cost_df['Model'].isin(label_systems)]['Publication date'],
    y=gpu_cost_df.loc[gpu_cost_df['Model'].isin(label_systems)]['Cost (inflation-adjusted)'],
    text=gpu_cost_df.loc[gpu_cost_df['Model'].isin(label_systems)]['Model'],
    mode='text',
    showlegend=False,
))
fig.add_trace(go.Scatter(
    x=tpu_cost_df.loc[tpu_cost_df['Model'].isin(label_systems)]['Publication date'],
    y=tpu_cost_df.loc[tpu_cost_df['Model'].isin(label_systems)]['Cost (inflation-adjusted)'],
    text=tpu_cost_df.loc[tpu_cost_df['Model'].isin(label_systems)]['Model'],
    mode='text',
    showlegend=False,
))

# Marker color
fig.update_traces(
    marker=dict(
        color='rgb(0,100,200)',
    ),
    selector=dict(mode='markers'),
)

# Shade in CI
fig.add_scatter(
    x=predicted_cost_df['Publication date'],
    y=10**predicted_cost_df['mean_ci_lower'],
    mode='lines',
    line=dict(width=0),
    showlegend=False,
)
fig.add_scatter(
    x=predicted_cost_df['Publication date'],
    y=10**predicted_cost_df['mean_ci_upper'],
    mode='lines',
    fill='tonexty',
    fillcolor='rgba(0,100,200,0.2)',
    line=dict(width=0),
    name='90% CI of mean',
)
fig.add_scatter(
    x=predicted_cost_df['Publication date'],
    y=10**predicted_cost_df['mean'],
    mode='lines',
    line=dict(color='rgb(0,100,200)'),
    name=f'Regression mean (growth rate: {10**reg_results.params[1]:.1f}x per year)',
)

fig.update_traces(textposition='top right')

# axis limits
# fig.update_xaxes(range=[pred_start_date, pred_end_date])
# fig.update_xaxes(range=['2010-01-01', '2026-01-01'])  # manual
# if estimation_method == 'hardware-acquisition':
#     fig.update_yaxes(range=[2, 10])
# else:
#     fig.update_yaxes(range=[1, 9])

# legend on bottom-right of the axes
fig.update_layout(
    legend=dict(
        x=0.45,
        y=0.05,
    )
)

# axis labels
fig.update_xaxes(title_text='Publication date')
fig.update_yaxes(title_text='Cost (2025 USD, log scale)')

# title
fig.update_layout(title_text=get_cost_plot_title(estimation_method, compute_threshold_method, compute_threshold))

# update size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
    title_font=dict(
        size=16,
    ),
    title_x=0.5,
)

# font size
fig.update_layout(
    font=dict(
        size=14,
    )
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=60, b=10))

print(f'Growth rate: {10**reg_results.params[1]:.6f}x per year')
print(f'90% CI: {10**reg_results.conf_int(alpha=0.1)[1][0]:.6f}x to {10**reg_results.conf_int(alpha=0.1)[1][1]:.6f}x')

save_plot(fig, results_dir, 'cost_regression')

fig.show()

Growth rate: 2.614501x per year
90% CI: 2.044495x to 3.343425x

# Cost components

In [61]:
cost_component_names = [
    'AI accelerator chip cost',
    'Other server components cost',
    'Cluster-level interconnect cost',
    'Energy cost',
]

In [62]:
for key in cost_component_names:
    component_cost_df[f"{key} (%)"] = component_cost_df[key] / component_cost_df['Cost'] * 100
component_cost_df['AI accelerator chip cost (%)']

NameError: name 'component_cost_df' is not defined

In [ ]:
cost_component_pc_names = [name + ' (%)' for name in cost_component_names]
filtered_component_cost_df = component_cost_df.dropna(subset=cost_component_pc_names).sort_values(by='Publication date')

In [ ]:
# Stacked bar chart of cost components, using component_cost_df
fig = px.bar(
    filtered_component_cost_df,
    x='Model',
    y=cost_component_pc_names,
    barmode='stack',
)

# axis labels
fig.update_xaxes(title_text='ML model')
fig.update_yaxes(title_text='% of amortized hardware CapEx + energy')
fig.update_layout(
    legend=dict(
        title_text='Cost component',
        x=0.60,
        y=0.05,
    )
)
# limits 0 to 100
fig.update_yaxes(range=[0, 100])

fig.update_yaxes(tickvals=list(range(0, 101, 10)))

# size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=40, b=10))

save_plot(fig, results_dir, 'cost_component_percentage')

fig.show()

In [ ]:
filtered_component_cost_df.head()

,Model,Domain,Task,Authors,Notability criteria,Notability criteria notes,Model accessibility,Link,Citations,Reference,...,PTB ppl,Cost,AI accelerator chip cost,Other server components cost,Cluster-level interconnect cost,Energy cost,AI accelerator chip cost (%),Other server components cost (%),Cluster-level interconnect cost (%),Energy cost (%)
2061,DeepSpeech2 (English),Speech,Speech recognition,"Dario Amodei, Rishita Anubhai, Eric Battenberg...",Highly cited,NaN,NaN,https://arxiv.org/abs/1512.02595,2853.0,Deep Speech 2: End-to-End Speech Recognition i...,...,NaN,185.456639,63.953273,40.930095,24.602271,55.971000,34.484219,22.069900,13.265781,30.180101
2001,GNMT,Language,Translation,"Yonghui Wu, Mike Schuster, Zhifeng Chen, Quoc ...",Highly cited,NaN,Hosted access (no API),https://arxiv.org/abs/1609.08144,6483.0,Google's Neural Machine Translation System: Br...,...,NaN,177459.232941,77894.044829,49852.188691,29965.165887,19747.833534,43.894050,28.092192,16.885662,11.128096
2000,Xception,Vision,Image classification,François Chollet,Highly cited,NaN,NaN,https://arxiv.org/abs/1610.02357,13038.0,Xception: Deep Learning with Depthwise Separab...,...,NaN,11554.506253,5064.230483,3241.107509,1948.165702,1301.002560,43.829051,28.050593,16.860657,11.259698
1985,PolyNet,Vision,Image classification,"X Zhang, Z Li, C Change Loy",SOTA improvement,"""The Very Deep PolyNet, designed following thi...",NaN,https://arxiv.org/abs/1611.05725,282.0,PolyNet: A Pursuit of Structural Diversity in ...,...,NaN,563.599706,178.564122,114.281038,68.692074,202.062472,31.682792,20.276987,12.188096,35.852125
1965,MoE-Multi,Language,"Language modeling,Translation","N Shazeer, A Mirhoseini, K Maziarz, A Davis","Highly cited,SOTA improvement","""On large language modeling and machine transl...",Unreleased,https://arxiv.org/abs/1701.06538,2037.0,Outrageously Large Neural Networks: The Sparse...,...,NaN,3538.189418,1519.646471,972.573741,584.594865,461.374341,42.949834,27.487894,16.522430,13.039843

In [ ]:
filtered_component_cost_df.to_csv(results_dir + 'cost_components.csv', index=False)

In [ ]:
# Average percentage for each component
filtered_component_cost_df[cost_component_pc_names].mean()

AI accelerator chip cost (%)           45.038389
Other server components cost (%)       29.130089
Cluster-level interconnect cost (%)    17.397544
Energy cost (%)                         8.433978
dtype: float64

In [ ]:
fig = px.bar(
    filtered_component_cost_df,
    x='Model',
    y='Energy cost (%)',
    barmode='stack',
    # labels='Cost %',
    # text='Energy cost %',
)
# axis labels
fig.update_xaxes(title_text='Model')
fig.update_yaxes(title_text='Energy cost (% of amortized hardware CapEx + energy)')
# fig.update_layout(
#     legend=dict(
#         title_text='Cost component',
#         x=0.75,
#         y=0.05,
#     )
# )
# limits 0 to 100
fig.update_yaxes(range=[0, 30])
# size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=40, b=10))

save_plot(fig, results_dir, 'energy_percentage')

fig.show()

In [ ]:
fig = px.scatter(
    filtered_component_cost_df,
    x='Publication date',
    y='Energy cost',
    text='Model',
)
# axis labels
fig.update_xaxes(title_text='Model')
fig.update_yaxes(title_text='Energy cost')
# log y
fig.update_yaxes(type='log')
# size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=40, b=10))

save_plot(fig, results_dir, 'energy_cost')

fig.show()

In [ ]:
from energy import energy_price

# Stacked bar chart of cost components, using component_cost_df
filtered_component_cost_df.loc[:, 'Energy (kWh)'] = [
    row['Energy cost'] / energy_price(row['Publication date'].year) 
    for _, row in filtered_component_cost_df.iterrows()
]
fig = px.scatter(
    filtered_component_cost_df,
    x='Publication date',
    y='Energy (kWh)',
    text='Model',
)
# log y
fig.update_yaxes(type='log')
# size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=40, b=10))

save_plot(fig, results_dir, 'energy_kwh')

fig.show()

In [ ]:
filtered_component_cost_df.columns

Index(['Model', 'Domain', 'Task', 'Authors', 'Notability criteria',
       'Notability criteria notes', 'Model accessibility', 'Link', 'Citations',
       'Reference',
       ...
       'Cost', 'AI accelerator chip cost', 'Other server components cost',
       'Cluster-level interconnect cost', 'Energy cost',
       'AI accelerator chip cost (%)', 'Other server components cost (%)',
       'Cluster-level interconnect cost (%)', 'Energy cost (%)',
       'Energy (kWh)'],
      dtype='object', length=108)

In [ ]:
filtered_component_cost_df = filtered_component_cost_df.dropna(subset=['Training hardware'])
power_col = 'Power capacity for final training run (kW)'
filtered_component_cost_df.loc[:, power_col] = [
    cluster_power_capacity(row['Training hardware'], row['Hardware quantity'], hardware_df, row['Organization'])
    for _, row in filtered_component_cost_df.iterrows()
]

fig = px.scatter(
    filtered_component_cost_df,
    x='Publication date',
    y=power_col,
    text='Model',
)
# log y
fig.update_yaxes(type='log')
# size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=40, b=10))

save_plot(fig, results_dir, 'power_capacity_kw')

fig.show()

In [ ]:
filtered_component_cost_df['Publication date (float)'] = datetime_to_float_year(
    pd.to_datetime(filtered_component_cost_df['Publication date'])
)

In [ ]:
power_reg_results = fit_ols_regression(
    filtered_component_cost_df,
    ['Publication date (float)'],
    power_col,
    logy=True
)
power_reg_results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.863
Model:                            OLS   Adj. R-squared:                  0.859
Method:                 Least Squares   F-statistic:                     233.0
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           1.51e-17
Time:                        15:15:52   Log-Likelihood:                -10.518
No. Observations:                  39   AIC:                             25.04
Df Residuals:                      37   BIC:                             28.36
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -717.4255     47.192    -15.202      0.000    -813.045    -621.806
x1             0.3564      0.023     15.263      0.000       0.309       0.404
==============================================================================
Omnibus:                        5.566   Durbin-Watson:                   1.953
Prob(Omnibus):                  0.062   Jarque-Bera (JB):                4.658
Skew:                           0.514   Prob(JB):                       0.0974
Kurtosis:                       4.345   Cond. No.                     1.83e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.83e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
with open(f'{results_dir}/power_regression_results.out', 'w') as f:
    with redirect_stdout(f):
        print_growth_rates(power_reg_results)
print_growth_rates(power_reg_results)

N=39.0
R^2=0.86
0.3564433491873348 OOMs/year (90% CI: 0.3170440986156087, 0.39584259975906083)
2.2721832248227765x/year (90% CI: 2.075124216561464x, 2.4879554515155515x)
doubling time of 10.13445742837872 months (90% CI: 9.12574834079638, 11.393872220745795)

In [ ]:
pred_start_year = 2015
pred_end_year = 2025
pred_start_date = f'{pred_start_year}-01-01'
pred_end_date = f'{pred_end_year}-01-01'

pred_years = pd.DataFrame({'Publication date (float)': np.linspace(pred_start_year, pred_end_year, 100)})
pred_years

    Publication date (float)
0                 2015.00000
1                 2015.10101
2                 2015.20202
3                 2015.30303
4                 2015.40404
..                       ...
95                2024.59596
96                2024.69697
97                2024.79798
98                2024.89899
99                2025.00000

[100 rows x 1 columns]

In [ ]:
predicted_power_df = get_predictions(power_reg_results, pred_years, ['Publication date (float)'])
predicted_power_df['Publication date'] = predicted_power_df['Publication date (float)'].apply(float_year_to_datetime)
predicted_power_df

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper,Publication date (float),Publication date
0,0.807834,0.144451,0.564132,1.051537,0.207307,1.408361,2015.00000,2015-01-01
1,0.843838,0.142253,0.603844,1.083833,0.244807,1.442870,2015.10101,2015-02-06
2,0.879843,0.140061,0.643547,1.116139,0.282284,1.477402,2015.20202,2015-03-15
3,0.915847,0.137874,0.683241,1.148454,0.319737,1.511957,2015.30303,2015-04-21
4,0.951852,0.135693,0.722925,1.180778,0.357168,1.546535,2015.40404,2015-05-28
...,...,...,...,...,...,...,...,...
95,4.228250,0.103442,4.053734,4.402766,3.652318,4.804182,2024.59596,2024-08-06
96,4.264254,0.105487,4.086289,4.442220,3.687268,4.841241,2024.69697,2024-09-12
97,4.300259,0.107544,4.118822,4.481696,3.722193,4.878325,2024.79798,2024-10-19
98,4.336263,0.109614,4.151335,4.521192,3.757091,4.915435,2024.89899,2024-11-25
99,4.372268,0.111695,4.183828,4.560707,3.791965,4.952570,2025.00000,2025-01-01

## Power plot

In [ ]:
label_systems = ['GNMT', 'AlphaGo Master', 'AlphaGo Zero', 'AlphaZero', 'DALL-E', 'GPT-3 175B (davinci)', 'PaLM (540B)', 'Llama 2-70B', 'Falcon 180B', 'GPT-4', 'Gemini 1.0 Ultra', 'Inflection-2']

fig = px.scatter(
    filtered_component_cost_df,
    x='Publication date',
    y=power_col,
    log_y=True,
)

# Marker color
fig.update_traces(
    marker=dict(
        color='rgb(0,100,200)',
    ),
    selector=dict(mode='markers'),
)

fig.add_scatter(
    x=filtered_component_cost_df.loc[filtered_component_cost_df['Model'].isin(label_systems)]['Publication date'],
    y=filtered_component_cost_df.loc[filtered_component_cost_df['Model'].isin(label_systems)][power_col],
    text=filtered_component_cost_df.loc[filtered_component_cost_df['Model'].isin(label_systems)]['Model'],
    mode='text',
    showlegend=False,
)

# Shade in CI
fig.add_scatter(
    x=predicted_power_df['Publication date'],
    y=10**predicted_power_df['mean_ci_lower'],
    mode='lines',
    line=dict(width=0),
    showlegend=False,
)
fig.add_scatter(
    x=predicted_power_df['Publication date'],
    y=10**predicted_power_df['mean_ci_upper'],
    mode='lines',
    fill='tonexty',
    fillcolor='rgba(0,100,200,0.2)',
    line=dict(width=0),
    name='90% CI of mean',
)
fig.add_scatter(
    x=predicted_power_df['Publication date'],
    y=10**predicted_power_df['mean'],
    mode='lines',
    line=dict(color='rgb(0,100,200)'),
    name=f'Regression mean (growth rate: {10**power_reg_results.params[1]:.1f}x per year)',
)

fig.update_traces(textposition='top center')

# axis limits
fig.update_xaxes(range=[pred_start_date, pred_end_date])
# fig.update_xaxes(range=['2015-01-01', '2025-01-01'])  # manual
# fig.update_yaxes(range=[1, 6])

# legend on bottom-right of the axes
fig.update_layout(
    legend=dict(
        x=0.45,
        y=0.05,
    )
)

# axis labels
fig.update_xaxes(title_text='Publication date')
fig.update_yaxes(title_text='Power (kW, log scale)')

# title
fig.update_layout(title_text='Cluster power required for final training run')

# update size
fig.update_layout(
    autosize=False,
    width=800,
    height=600,
    title_font=dict(
        size=16,
    ),
    title_x=0.5,
)

# font size
fig.update_layout(
    font=dict(
        size=14,
    )
)

# margins
fig.update_layout(margin=dict(l=10, r=10, t=60, b=10))

save_plot(fig, results_dir, 'power_regression')

fig.show()